# Generated by Django 5.0.3 on 2025-02-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=6),
        ),
    ]
