# Generated by Django 5.0.3 on 2025-02-08 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazoff', '0002_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_sold', to='amazoff.people'),
        ),
    ]
