# Generated by Django 5.0.3 on 2025-02-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazoff', '0004_alter_product_sellerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellerid',
            new_name='seller',
        ),
    ]
