# Generated by Django 5.0.3 on 2025-02-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazoff', '0005_rename_sellerid_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media/product_images/'),
        ),
    ]
