# Generated by Django 5.0.3 on 2025-02-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazoff', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
