# Generated by Django 5.0.3 on 2025-02-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazoff', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
