# Generated by Django 5.1.6 on 2025-02-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazoff', '0010_category_remove_product_mainaddress_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='isgift',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='isselected',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
